version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: thefaucet
      POSTGRES_USER: thefaucet
      POSTGRES_PASSWORD: thefaucet_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thefaucet -d thefaucet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
