[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/"
]

# Solidity version
solc_version = "0.8.20"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Enable IR to fix stack too deep errors
via_ir = true

# Gas reporting
gas_reports = ["*"]

# Test settings
fuzz_runs = 1000
verbosity = 4

# File system permissions
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./src/deployments" }
]
